"""Rivals under the bounded prover K: does incompleteness remove the bridge-less obstruction?
Spec specs/2026-10-05-rivals-under-k.md (reviewed, reviews/2026-10-05-rivals-under-k-gpt-6.1-sol.md);
predictions predictions/2026-10-05-rivals-under-k.md.

Finite-cutoff (n = 8), finite-horizon evidence about the bridge-less obstruction relative to FairBot's pair.

Tables.  The modal language L_8 (610 canonical sources, `gl_proofs.box_tables(8)`), played under the free box (the
GL+Def table) or under K at global budget b (guard at the reader's own budget; `runs/k-at-n8/kval_n8_b{b}.npy`,
regenerated by `src/k_at_n8.py ktables` if absent).  Behavioural classes: canonical sources with identical directed
rows and columns of the play table (payoff identity in the PD, as modal.ModalProvider), representative = min (bits,
canon), ordered by mass.  Masses: raw (the infinite length prior, shell s has mass 1/(2 s^2)) and cut (normalized
within L_8).

Definitions (spec, [after review]).  A = {FairBot = BOX(THEM(ME)), BOX1(THEM(ME))} located by source.
  cooperative class   self-cooperates and its row is not all-C (static, as bridgeless_rivals); the kernel's
                      certification flag is rival_islands' (self-cooperates, not the class of C).
  establisher         cooperative and defects on D.
  rival of A          an establisher that mutually defects with some member of A; full: with both; half: with one.
  direct bridge       of (A, R): a cooperative class, not in A, mutually cooperating with FairBot, BOX1(THEM(ME)) and R.
  bridge-less         no direct bridge.
  mediator path       a path of length <= 3 from R to A in the establisher mutual-cooperation graph (nodes: establishers
                      and A); reported also over the cooperative-class graph.
  zero transition     one-migrant fixation of R into A_j and of A_j into R exactly 0 under the kernel's law (N = 200),
                      for each A_j R mutually defects with; below threshold: < 1e-12 but positive.
  mediator (old)      cooperative, not a bridge, not in A, and FairBot, BOX1(THEM(ME)) and R all cooperate with it.
  A-faked             some A_j strictly invades R (A_j defects on R while R cooperates with A_j).
  hard bridge-less    bridge-less, no mediator, not A-faked.
  new rival under K   a canonical source that is a rival of A under K's table and not under the free table.

    python3 src/rivals_under_k.py static            # tables, lumping check, free reproduction, screening
"""
import argparse, gzip, json, math, os, re, sys, time, zlib
from collections import Counter, defaultdict, deque
import numpy as np
sys.path.insert(0, os.path.dirname(__file__))

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RUNS = os.path.join(ROOT, 'runs')
KDIR = os.path.join(RUNS, 'k-at-n8')
STATIC = os.path.join(RUNS, 'rivals-under-k-static.json')
W = 0.3
NCUT = 8
PDP = np.array([[-1.0, 1.0], [-2.0, 0.0]])       # pay[a][b], level order (D, C)
FB, FB1 = 'BOX(THEM(ME))', 'BOX1(THEM(ME))'
PSTAR = 'and(BOX1(THEM(ME)),not(BOX(THEM(ME))))'
ARMS = ('free', 'K16', 'K4', 'K54')
PSTAR_RE = re.compile(r'^and\(BOX1\(THEM\((.+)\)\),not\(BOX\(THEM\((.+)\)\)\)\)$')


def budget(arm):
    return None if arm == 'free' else int(arm[1:])


def retained(n):
    return sum(1 / (2 * s * s) for s in range(1, n + 1))


# ------------------------------------------------------------------ tables
_L = {}


def lang():
    if 'L' not in _L:
        import k_at_n8 as K8
        L, val, hc, hd = K8.tables(NCUT)
        _L['L'] = L; _L['free'] = val.astype(np.int8)
    return _L['L']


def canon_val(arm):
    lang()
    if arm == 'free':
        return _L['free']
    p = os.path.join(KDIR, 'kval_n%d_b%d.npy' % (NCUT, budget(arm)))
    if not os.path.exists(p):
        raise SystemExit('missing %s: regenerate with python3 src/k_at_n8.py ktables --budgets %d' % (p, budget(arm)))
    return np.load(p).astype(np.int8)


_D = {}


def arm_table(arm):
    """Class data for an arm: V (class play matrix, uint8), mu (cut), raw, names, idx, cls_of (canon -> class),
    members, flags.  Compatible with rival_islands.restrict / tags_for."""
    if arm in _D:
        return _D[arm]
    L = lang(); v = canon_val(arm)
    Kc = v.shape[0]
    sig = defaultdict(list)
    for c in range(Kc):
        sig[(v[c].tobytes(), v[:, c].tobytes())].append(c)
    reps = []
    for mem in sig.values():
        rep = min(mem, key=lambda c: (L.bits_canon[c], c))
        reps.append((rep, mem, float(L.mu_canon[mem].sum())))
    reps.sort(key=lambda t: -t[2])
    idx = np.array([t[0] for t in reps], np.int64)
    V = np.ascontiguousarray(v[np.ix_(idx, idx)]).astype(np.uint8)
    raw = np.array([t[2] for t in reps])
    names = [L.rep[c] for c in idx]
    cls_of = np.full(Kc, -1, np.int64)
    for j, t in enumerate(reps):
        cls_of[np.array(t[1])] = j
    K = len(names)
    selfc = np.diagonal(V).astype(bool).copy()
    canon_idx = {s: i for i, s in enumerate(L.rep)}
    iC = int(cls_of[canon_idx['C']]); iD = int(cls_of[canon_idx['D']])
    allc_row = V.all(1).astype(bool)
    allc_k = np.zeros(K, bool); allc_k[iC] = True
    vD = V[:, iD].astype(bool)
    d = dict(arm=arm, n=NCUT, V=V, raw=raw, mu=raw / raw.sum(), names=names, idx={x: i for i, x in enumerate(names)},
             reps=idx, cls_of=cls_of, members=[t[1] for t in reps], canon_idx=canon_idx, iC=iC, iD=iD, selfc=selfc,
             allc_row=allc_row,
             # static flags (bridgeless_rivals): cooperative = self-cooperating, row not all-C
             coop_s=selfc & ~allc_row, est_s=selfc & ~vD & ~allc_row,
             # kernel flags (rival_islands.cls): cooperative = self-cooperating, not the class of C
             coop=selfc & ~allc_k, est=selfc & ~vD & ~allc_k)
    d['src_cls'] = lambda s: int(cls_of[canon_idx[s]])
    _D[arm] = d
    return d


def lumping_check(arm, nsample=1000, seed=7):
    """(i) every class has identical directed rows and columns for all its members (exhaustive, bytewise);
    (ii) source masses and seed probabilities preserved; (iii) establishment, rival and bridge tests agree between
    the lumped and the source-level tables on a sample of sources (all 610 when nsample >= 610)."""
    L = lang(); v = canon_val(arm); d = arm_table(arm)
    Kc = v.shape[0]
    bad_rows = 0
    for k, mem in enumerate(d['members']):
        r0 = d['reps'][k]
        for c in mem:
            if not (np.array_equal(v[c], v[r0]) and np.array_equal(v[:, c], v[:, r0])):
                bad_rows += 1
    # masses and seed probabilities: class probability = sum of member probabilities
    mu_c = L.mu_canon / L.mu_canon.sum()
    agg = np.zeros(len(d['names'])); np.add.at(agg, d['cls_of'], mu_c)
    mass_err = float(np.abs(agg - d['mu']).max())
    raw_err = float(abs(d['raw'].sum() - L.mu_canon.sum()))
    # seed law: one island of N = 200 drawn at source level and lumped versus drawn at class level (same law);
    # checked by comparing first moments over 2,000 draws each
    rng = np.random.default_rng(seed)
    a = np.zeros(len(agg)); b = np.zeros(len(agg))
    for _ in range(2000):
        x = rng.multinomial(200, mu_c); y = np.zeros(len(agg)); np.add.at(y, d['cls_of'], x); a += y
        b += rng.multinomial(200, d['mu'])
    seed_z = float(np.max(np.abs(a - b) / np.sqrt(np.maximum(a + b, 1))))
    # source-level tests
    vb = v.astype(bool)
    selfc = np.diagonal(vb).copy(); allc = vb.all(1)
    iDc = d['canon_idx']['D']
    coop = selfc & ~allc; est = coop & ~vb[:, iDc]
    f0, f1 = d['canon_idx'][FB], d['canon_idx'][FB1]
    MC = lambda x: vb[x, :] & vb[:, x]
    MD = lambda x: ~vb[x, :] & ~vb[:, x]
    rival = est & (MD(f0) | MD(f1))
    notA = np.ones(Kc, bool)
    notA[(d['cls_of'] == d['cls_of'][f0]) | (d['cls_of'] == d['cls_of'][f1])] = False
    src = np.arange(Kc) if nsample >= Kc else rng.choice(Kc, nsample, replace=False)
    S = screen(arm, light=True)
    rv = {r['cls']: r for r in S['rivals']}
    mism = Counter()
    for s in src:
        k = int(d['cls_of'][s])
        if bool(est[s]) != bool(d['est_s'][k]): mism['est'] += 1
        if bool(rival[s]) != (k in rv): mism['rival'] += 1
        if rival[s]:
            br = coop & notA & MC(f0) & MC(f1) & MC(s)
            bm = float(mu_c[br].sum())
            if (bm > 0) != (rv[k]['n_bridges'] > 0): mism['bridge'] += 1
            if abs(bm - rv[k]['bridge_mass']) > 1e-12: mism['bridge_mass'] += 1
    return dict(arm=arm, n_classes=len(d['names']), n_canon=Kc, members_bad=bad_rows, mass_err=mass_err,
                raw_err=raw_err, seed_moment_max_z=seed_z, sources_tested=int(len(src)), mismatches=dict(mism),
                ok=bool(bad_rows == 0 and mass_err < 1e-12 and not mism))


def free_reproduction():
    """The free class table built here must equal the existing n = 8 free class table (modal.build(8), the table
    almost_all_seeds.arm_data('modal', 8) / seeds_in_n use): classes, names, order, payoffs, masses."""
    import modal as M
    Lm, val, worlds, prov = M.build(NCUT)
    d = arm_table('free')
    U = PDP[d['V'].astype(int), d['V'].T.astype(int)]
    same_names = list(prov.names) == d['names']
    mu_p = np.array([c[2] for c in prov.classes])
    out = dict(n_classes_here=len(d['names']), n_classes_modal=len(prov.names), names_equal=bool(same_names),
               canon_val_equal=bool((val.astype(np.int8) == _L['free']).all()))
    if same_names:
        out['U_equal'] = bool(np.array_equal(U, prov.Ufull)); out['mu_maxdiff'] = float(np.abs(mu_p - d['mu']).max())
    else:
        pos = {x: i for i, x in enumerate(prov.names)}
        common = [x for x in d['names'] if x in pos]
        out['common'] = len(common)
    out['ok'] = bool(same_names and out.get('U_equal') and out.get('mu_maxdiff', 1) < 1e-12 and out['canon_val_equal'])
    return out


# ------------------------------------------------------------------ static screening
def fixk(N, k, uqq, uqa, uaq, uaa):
    import rival_islands as R
    return R.fix_k(N, W, k, uqq, uqa, uaq, uaa)


def rho_pair(N, vq, vx):
    """One-migrant fixation of a self-cooperator q into all-x (x self-cooperating) given q's play vq against x and
    x's play vx against q (the kernel's law)."""
    return fixk(N, 1, 0.0, PDP[vq, vx], PDP[vx, vq], 0.0)


def pstar_family(d, k):
    return any(PSTAR_RE.match(lang().rep[c]) for c in d['members'][k])


def bfs(adj, sources):
    dist = -np.ones(adj.shape[0], np.int64); dq = deque()
    for s in sources:
        dist[s] = 0; dq.append(s)
    while dq:
        u = dq.popleft()
        for v in np.nonzero(adj[u] & (dist < 0))[0]:
            dist[v] = dist[u] + 1; dq.append(v)
    return dist


def components(adj):
    n = adj.shape[0]; comp = -np.ones(n, np.int64); c = 0
    for s in range(n):
        if comp[s] >= 0: continue
        comp[s] = c; st = [s]
        while st:
            u = st.pop()
            for v in np.nonzero(adj[u] & (comp < 0))[0]:
                comp[v] = c; st.append(v)
        c += 1
    return comp, c


def screen(arm, light=False, Ns=(200, 400), refs=(FB, FB1)):
    d = arm_table(arm)
    V = d['V'].astype(bool); K = V.shape[0]
    mu, raw, nm = d['mu'], d['raw'], d['names']
    a0, a1 = d['src_cls'](refs[0]), d['src_cls'](refs[1])
    coop, est = d['coop_s'], d['est_s']
    MC = lambda x: V[x, :] & V[:, x]
    MD = lambda x: ~V[x, :] & ~V[:, x]
    notA = np.ones(K, bool); notA[[a0, a1]] = False
    netA = coop & MC(a0) & MC(a1)
    md0, md1 = MD(a0), MD(a1)
    riv = est & (md0 | md1); full = est & md0 & md1
    R_ = np.nonzero(riv)[0]; R_ = R_[np.argsort(-mu[R_])]
    # establisher graph (establishers and A) and cooperative graph
    E = np.nonzero(est | ~notA)[0]
    posE = -np.ones(K, np.int64); posE[E] = np.arange(len(E))
    adjE = V[np.ix_(E, E)] & V[np.ix_(E, E)].T
    np.fill_diagonal(adjE, False)
    distE = bfs(adjE, [posE[a0], posE[a1]])
    Cc = np.nonzero(coop | ~notA)[0]
    posC = -np.ones(K, np.int64); posC[Cc] = np.arange(len(Cc))
    adjC = V[np.ix_(Cc, Cc)] & V[np.ix_(Cc, Cc)].T
    np.fill_diagonal(adjC, False)
    distC = bfs(adjC, [posC[a0], posC[a1]])
    rows = []; union_br = np.zeros(K, bool)
    for r in R_:
        br = netA & MC(r) & notA
        union_br |= br
        bi = np.nonzero(br)[0]
        hb = int(bi[np.argmax(mu[bi])]) if len(bi) else -1
        medm = coop & notA & ~br & V[a0, :] & V[a1, :] & V[r, :]; medm[r] = False
        mi = np.nonzero(medm)[0]
        afaked = [bool(V[r, a] and not V[a, r]) for a in (a0, a1)]
        row = dict(name=nm[r], cls=int(r), mu=float(mu[r]), raw=float(raw[r]), full=bool(full[r]),
                   md=[bool(md0[r]), bool(md1[r])], pstar_family=bool(pstar_family(d, r)),
                   n_members=len(d['members'][r]),
                   n_bridges=int(br.sum()), bridge_mass=float(mu[br].sum()), bridge_raw=float(raw[br].sum()),
                   heaviest_bridge=nm[hb] if hb >= 0 else None, heaviest_bridge_mu=float(mu[hb]) if hb >= 0 else 0.0,
                   safe_bridge_mass=float(mu[br & est].sum()),
                   n_mediators=int(len(mi)), mediator_mass=float(mu[mi].sum()),
                   A_faked=bool(any(afaked)), A_faked_by=afaked,
                   path_est=int(distE[posE[r]]) if distE[posE[r]] >= 0 else None,
                   path_coop=int(distC[posC[r]]) if distC[posC[r]] >= 0 else None)
        if not light:
            prey = V[:, r] & ~V[r, :]
            row['prey_netA_mass'] = float(mu[prey & netA].sum())
            row['prey_netA_top'] = [(nm[x], float(mu[x])) for x in sorted(np.nonzero(prey & netA)[0], key=lambda x: -mu[x])[:3]]
            row['bridges_top'] = [(nm[x], float(mu[x])) for x in sorted(bi, key=lambda x: -mu[x])[:3]]
            row['mediator_top'] = [(nm[x], float(mu[x])) for x in sorted(mi, key=lambda x: -mu[x])[:3]]
            fx = {}
            for N in Ns:
                tr = []
                for j, a in enumerate((a0, a1)):
                    if not (md0, md1)[j][r]:
                        continue
                    into_a = rho_pair(N, int(V[r, a]), int(V[a, r]))
                    into_r = rho_pair(N, int(V[a, r]), int(V[r, a]))
                    tr += [into_a, into_r]
                cat = 'zero' if all(x == 0.0 for x in tr) else ('below' if max(tr) < 1e-12 else 'positive')
                fx[str(N)] = dict(rho=tr, cat=cat)
            row['fix'] = fx
        rows.append(row)
    if not light:
        for row in rows:
            r = row['cls']; prey = V[:, r] & ~V[r, :]
            row['prey_bridges_mass'] = float(mu[prey & union_br].sum())
    tot = float(mu[R_].sum()); totr = float(raw[R_].sum())

    def share(sel):
        m = float(sum(x['mu'] for x in rows if sel(x))); mr = float(sum(x['raw'] for x in rows if sel(x)))
        return dict(n=int(sum(1 for x in rows if sel(x))), mu=m, raw=mr, share=m / tot if tot else None)
    agg = dict(
        direct_bridgeless=share(lambda x: x['n_bridges'] == 0),
        hard_bridgeless=share(lambda x: x['n_bridges'] == 0 and x['n_mediators'] == 0 and not x['A_faked']),
        no_mediator_path=share(lambda x: x['path_est'] is None or x['path_est'] > 3),
        no_mediator_path_coop=share(lambda x: x['path_coop'] is None or x['path_coop'] > 3),
        A_faked=share(lambda x: x['A_faked']),
        pstar_family=share(lambda x: x['pstar_family']),
        pstar_family_bridgeless=share(lambda x: x['pstar_family'] and x['n_bridges'] == 0),
        full=share(lambda x: x['full']), half=share(lambda x: not x['full']))
    if not light:
        for N in Ns:
            for c in ('zero', 'below', 'positive'):
                agg['fix%s_%s' % (N, c)] = share(lambda x, c=c, N=N: x['fix'][str(N)]['cat'] == c)
    out = dict(arm=arm, K=K, n_canon=int(len(d['cls_of'])), n_rivals=len(rows), n_full=int(full.sum()),
               rival_mu=tot, rival_raw=totr, est_mu=float(mu[est].sum()), est_n=int(est.sum()),
               coop_n=int(coop.sum()), netA_mu=float(mu[netA].sum()), union_bridge_mu=float(mu[union_br].sum()),
               allc_row_classes=int(d['allc_row'].sum()), A=[nm[a0], nm[a1]],
               A_selfcoop=[bool(V[a0, a0]), bool(V[a1, a1])], A_mutual=bool(V[a0, a1] and V[a1, a0]),
               agg=agg, rivals=rows)
    if not light:
        comp, nc = components(adjE)
        cA = comp[posE[a0]]
        sizes = Counter(comp.tolist())
        out['graph_est'] = dict(nodes=int(len(E)), components=int(nc),
                                largest=[int(s) for _, s in sizes.most_common(5)],
                                A_component_nodes=int(sizes[cA]),
                                A_component_mu=float(mu[E[comp == cA]].sum()), est_mu=float(mu[E].sum()),
                                A_connected_to_each_other=bool(comp[posE[a0]] == comp[posE[a1]]),
                                path_hist_count={str(k): int(v) for k, v in Counter(distE.tolist()).items()},
                                path_hist_mu={str(k): float(mu[E[distE == k]].sum()) for k in sorted(set(distE.tolist()))})
        compC, ncC = components(adjC)
        sizesC = Counter(compC.tolist())
        out['graph_coop'] = dict(nodes=int(len(Cc)), components=int(ncC), largest=[int(s) for _, s in sizesC.most_common(5)],
                                 path_hist_count={str(k): int(v) for k, v in Counter(distC.tolist()).items()})
        # incompatible establisher pairs (mutual defection) not involving A, by mass
        Ve = V[np.ix_(E, E)]
        DD = ~Ve & ~Ve.T; np.fill_diagonal(DD, False)
        iu = np.argwhere(np.triu(DD, 1))
        pm = mu[E[iu[:, 0]]] * mu[E[iu[:, 1]]] if len(iu) else np.zeros(0)
        out['md_pairs'] = dict(n=int(len(iu)), mass=float(pm.sum()),
                               top=[(nm[E[iu[k, 0]]], nm[E[iu[k, 1]]], float(pm[k])) for k in np.argsort(-pm)[:10]])
    return out


def new_rivals(arm, ref='free'):
    """Sources (canonical programs) that are rivals of A under `arm` and not under `ref`, and the reverse."""
    L = lang()
    S = {a: screen(a, light=True) for a in (arm, ref)}
    D = {a: arm_table(a) for a in (arm, ref)}
    rv = {a: {r['cls']: r for r in S[a]['rivals']} for a in (arm, ref)}
    is_r = {a: np.array([int(D[a]['cls_of'][c]) in rv[a] for c in range(len(L.rep))]) for a in (arm, ref)}
    raw = L.mu_canon; Z = raw.sum()
    out = {}
    for key, sel in (('new', is_r[arm] & ~is_r[ref]), ('lost', is_r[ref] & ~is_r[arm]), ('kept', is_r[arm] & is_r[ref])):
        src = np.nonzero(sel)[0]
        items = []
        for c in sorted(src, key=lambda c: -raw[c]):
            ka = int(D[arm]['cls_of'][c]); kr = int(D[ref]['cls_of'][c])
            ra = rv[arm].get(ka); rr = rv[ref].get(kr)
            items.append(dict(src=L.rep[c], raw=float(raw[c]), cut=float(raw[c] / Z),
                              bridgeless_arm=(ra['n_bridges'] == 0) if ra else None,
                              hard_arm=(ra['n_bridges'] == 0 and ra['n_mediators'] == 0 and not ra['A_faked']) if ra else None,
                              bridgeless_ref=(rr['n_bridges'] == 0) if rr else None,
                              pstar=bool(PSTAR_RE.match(L.rep[c])),
                              class_arm=D[arm]['names'][ka], class_ref=D[ref]['names'][kr]))
        out[key] = dict(n=len(items), raw=float(raw[src].sum()), cut=float(raw[src].sum() / Z),
                        bridgeless_cut=float(sum(x['cut'] for x in items if x['bridgeless_arm'])),
                        hard_cut=float(sum(x['cut'] for x in items if x['hard_arm'])),
                        items=items[:60])
    return out


def static_main(a):
    t0 = time.time()
    res = dict(n=NCUT, retained=retained(NCUT), arms=list(ARMS))
    res['free_reproduction'] = free_reproduction()
    print('free reproduction', res['free_reproduction'], flush=True)
    res['lumping'] = {}
    for arm in ARMS:
        res['lumping'][arm] = lumping_check(arm)
        print('lumping', res['lumping'][arm], flush=True)
    res['screen'] = {}
    for arm in ARMS:
        s = screen(arm)
        res['screen'][arm] = s
        g = s['agg']
        print('[%s] %d classes, %d est (mu %.4f), %d rivals (%d full), rival mu %.3g; direct bridge-less %d share %.3f; '
              'hard %.3f; P* family %.3f; no path<=3 %.3f; graph comps %d' % (
                  arm, s['K'], s['est_n'], s['est_mu'], s['n_rivals'], s['n_full'], s['rival_mu'],
                  g['direct_bridgeless']['n'], g['direct_bridgeless']['share'] or 0, g['hard_bridgeless']['share'] or 0,
                  g['pstar_family']['share'] or 0, g['no_mediator_path']['share'] or 0, s['graph_est']['components']), flush=True)
    # b = 4 supplement: A is not mutually cooperating there (soft cliques); rivals of each member alone
    res['screen_single'] = {}
    for arm in ARMS:
        for ref in (FB, FB1):
            s = screen(arm, refs=(ref, ref))
            s.pop('rivals_full', None)
            res['screen_single']['%s|%s' % (arm, ref)] = dict((k, v) for k, v in s.items() if k != 'md_pairs')
            g = s['agg']
            print('[%s, A = {%s}] %d rivals, rival mu %.3g, direct bridge-less share %.3f, hard %.3f' % (
                arm, ref, s['n_rivals'], s['rival_mu'], g['direct_bridgeless']['share'] or 0, g['hard_bridgeless']['share'] or 0), flush=True)
    res['new_rivals'] = {arm: new_rivals(arm) for arm in ARMS if arm != 'free'}
    for arm, v in res['new_rivals'].items():
        print('[%s vs free] new %d (cut %.3g, bridge-less %.3g), lost %d (cut %.3g), kept %d' % (
            arm, v['new']['n'], v['new']['cut'], v['new']['bridgeless_cut'], v['lost']['n'], v['lost']['cut'], v['kept']['n']), flush=True)
    # P* under each arm: class, self-play, plays against A, D
    L = lang(); res['pstar'] = {}
    for arm in ARMS:
        d = arm_table(arm); k = d['src_cls'](PSTAR); V = d['V']
        a0, a1 = d['src_cls'](FB), d['src_cls'](FB1)
        res['pstar'][arm] = dict(cls=d['names'][k], n_members=len(d['members'][k]), cls_mu=float(d['mu'][k]),
                                 src_mu=float(L.mu_canon[d['canon_idx'][PSTAR]] / L.mu_canon.sum()),
                                 self=int(V[k, k]), vs_FB=[int(V[k, a0]), int(V[a0, k])], vs_FB1=[int(V[k, a1]), int(V[a1, k])],
                                 vs_D=int(V[k, d['iD']]), vs_C=int(V[k, d['iC']]), same_class_as_D=bool(k == d['iD']),
                                 row_equals_D_row=bool(np.array_equal(V[k], V[d['iD']])),
                                 col_differs_from_D=int((V[:, k] != V[:, d['iD']]).sum()))
        # P*'s prey (classes cooperating with P* while P* defects on them) beyond D's prey
        prey = (V[:, k] == 1) & (V[k, :] == 0); preyD = (V[:, d['iD']] == 1)
        extra = prey & ~preyD
        res['pstar'][arm].update(
            prey_mu=float(d['mu'][prey].sum()), prey_not_D_mu=float(d['mu'][extra].sum()), prey_not_D_n=int(extra.sum()),
            prey_est_mu=float(d['mu'][prey & d['est_s']].sum()), prey_est_n=int((prey & d['est_s']).sum()),
            prey_est_top=[(d['names'][x], float(d['mu'][x])) for x in sorted(np.nonzero(prey & d['est_s'])[0], key=lambda x: -d['mu'][x])[:6]],
            D_prey_not_pstar_mu=float(d['mu'][preyD & ~prey].sum()))
    res['t'] = time.time() - t0
    json.dump(res, open(STATIC, 'w'), indent=1, default=str)
    print('saved %s (%.0fs)' % (STATIC, time.time() - t0))


# ------------------------------------------------------------------ lottery (dynamics)
# Kernel: rival_islands._kern unchanged (exact skipping, exact lumping, ancestry labels, strong-holder log), with the
# arm's class table.  PD, w = 0.3, eps = 0, complete island graph, generation = I*N births, horizon 1e5.
# Seeds are drawn at the source level (iid canonical programs from the length prior at n = 8) and lumped by the arm's
# classes, so the same rep gives the same programs in every arm (paired seeds; runs are still the independent units).
# Forced founders replace one uniformly chosen seed individual on each forced island (N kept).  A tracked lineage is a
# duplicate column of its class carrying tag 1 (tags have no dynamic effect; lumping never merges different tags), so
# the forced founders' descendants are followed exactly, separately from natural copies of the same class.
SALT = 20261008
GENS = 100000
EXPS = ('cal', 'nat', 'pos', 'pstar', 'dctl', 'iid', 'bl', 'cont', 'time')
PRESETS = ('iid', 'dense', 'sparse')
CALIB = os.path.join(RUNS, 'rivals-under-k-calib.json')
POSCTRL = 'and(BOX(THEM(ME)),BOXD1(THEM(^D)))'    # the heaviest bridged rival of A under K at b = 16 (static screen)


def chash(x):
    return 0 if x is None else zlib.crc32(x.encode()) % 100003


def seeds(exp, N, I, mN, rep, forced, preset):
    """rs: the initial seed (depends on N, I, rep only: shared by arms, mN, presets and m = 0 references);
    rs2: the founder placement; ss: the kernel stream (independent of the arm and of the horizon, so a longer horizon
    continues a run)."""
    pc = PRESETS.index(preset)
    rs = [SALT, N, I, rep]
    rs2 = [SALT + 1, N, I, rep, chash(forced), pc]
    ex = 'nat' if exp == 'cont' else exp
    ss = (1000003 * rep + 7919 * EXPS.index(ex) + 104729 * pc + 13 * N + 17 * I + int(round(mN * 1000))
          + 31 * chash(forced) + SALT) % (2 ** 31 - 1)
    return rs, rs2, ss


def build_init(d, N, I, forced, preset, rs, rs2):
    """Canonical iid seed, lumped by the arm's classes; forced founders by replacement of one uniformly chosen seed
    individual per forced island.  Returns init over classes and the per-island founder count (0/1)."""
    L = lang()
    mu_c = L.mu_canon / L.mu_canon.sum()
    rng = np.random.default_rng(rs)
    Kc = len(mu_c); K = len(d['names'])
    initc = np.zeros((I, Kc), np.int64)
    for i in range(I):
        initc[i] = rng.multinomial(N, mu_c)
    fmask = np.zeros(I, np.int64)
    if forced is not None and preset != 'iid':
        rng2 = np.random.default_rng(rs2)
        for i in range(I):
            if preset == 'dense' or (preset == 'sparse' and i < I // 4):
                u = rng2.integers(N)
                c = int(np.searchsorted(np.cumsum(initc[i]), u, side='right'))
                initc[i, c] -= 1
                fmask[i] = 1
    init = np.zeros((I, K), np.int64)
    for i in range(I):
        np.add.at(init[i], d['cls_of'], initc[i])
    return init, fmask


def a_ref(d, R):
    a0, a1 = d['src_cls'](FB), d['src_cls'](FB1)
    V = d['V']
    return a1 if (V[R, a1] == 0 and V[a1, R] == 0) else a0


def restrict(d, init, fmask, fcls, mode, A=None, B=None):
    """Support (with an appended duplicate column for a tracked lineage), payoffs, flags, tags, initial counts.
    mode: 'none' (tags 0), 'track' (tag 1 on the duplicate only), 'pair' (rival_islands tags for (A, B); the forced
    copies are added to their own class)."""
    import rival_islands as R_
    tot = init.sum(0)
    sup = set(int(x) for x in np.nonzero(tot > 0)[0])
    if mode == 'pair' and fcls is not None:
        sup.add(int(fcls))
    for x in (A, B):
        if x is not None:
            sup.add(int(x))
    sup = sorted(sup)
    ext = list(sup)
    if mode == 'track':
        ext.append(int(fcls))
    ext = np.array(ext, np.int64)
    Vs = d['V'][np.ix_(ext, ext)].astype(np.int64)
    U = np.ascontiguousarray(PDP[Vs, Vs.T])
    PCC = np.ascontiguousarray((Vs * Vs.T).astype(float))
    coop = d['coop'][ext].copy()
    if mode == 'pair':
        tag = R_.tags_for(d, np.array(sup, np.int64), A, B)
    else:
        tag = np.zeros(len(ext), np.int64)
        if mode == 'track':
            tag[-1] = 1
    li = np.zeros((init.shape[0], len(ext)), np.int64)
    li[:, :len(sup)] = init[:, sup]
    if fcls is not None:
        if mode == 'track':
            li[:, -1] = fmask
        elif mode == 'pair':
            li[:, sup.index(int(fcls))] += fmask
    return ext, U, PCC, coop, tag, np.ascontiguousarray(li)


def sep_intervals(trace):
    """Separation episodes from the kernel's per-check generic separation flag (col 8)."""
    g = trace[:, 0]; f = trace[:, 8] > 0.5
    if not f.any():
        return dict(ever=False, n_episodes=0, first=-1, last_sep=-1, resolved_at=-1, sep_at_end=False, sep_checks=0)
    on = np.nonzero(f)[0]
    episodes = int(1 + np.sum(np.diff(on) > 1))
    last = int(on[-1])
    sep_end = bool(f[-1])
    return dict(ever=True, n_episodes=episodes, first=int(g[on[0]]), last_sep=int(g[last]),
                resolved_at=-1 if sep_end else int(g[last + 1]), sep_at_end=sep_end, sep_checks=int(f.sum()))


_SCR = {}


def scr(arm):
    if arm not in _SCR:
        S = screen(arm, light=True)
        _SCR[arm] = {r['cls']: r for r in S['rivals']}
    return _SCR[arm]


def classify_pair(d, ga, gb):
    """Static type of a separated pair (global class indices): A-network membership, the rival and its type."""
    V = d['V'].astype(bool)
    a0, a1 = d['src_cls'](FB), d['src_cls'](FB1)
    inA = [bool(x in (a0, a1) or (V[x, a0] and V[a0, x] and V[x, a1] and V[a1, x])) for x in (ga, gb)]
    rv = scr(d['arm'])
    out = dict(inA=inA)
    cand = [x for x, ia in zip((ga, gb), inA) if not ia and x in rv]
    if any(inA) and cand:
        r = rv[cand[0]]
        out.update(kind='A-rival', rival=r['name'], rival_bridgeless=r['n_bridges'] == 0, rival_pstar=r['pstar_family'],
                   rival_hard=bool(r['n_bridges'] == 0 and r['n_mediators'] == 0 and not r['A_faked']), rival_mu=r['mu'],
                   rival_sources=[lang().rep[c] for c in d['members'][cand[0]]][:6], rival_g=int(cand[0]))
    elif any(x in rv for x in (ga, gb)):
        out.update(kind='rival-vs-nonA', rival=d['names'][[x for x in (ga, gb) if x in rv][0]])
    else:
        out.update(kind='non-A')
    return out


def job(j):
    import rival_islands as R_
    import island_path as IP
    exp, arm, N, I, mN, rep, gens, forced, preset = j
    d = arm_table(arm); nm = d['names']
    rs, rs2, ss = seeds(exp, N, I, mN, rep, forced, preset)
    init, fmask = build_init(d, N, I, forced, preset, rs, rs2)
    fcls = d['src_cls'](forced) if forced is not None else None
    mode = 'none'; A = B = None
    if exp in ('pstar', 'dctl'):
        mode = 'track'
    elif exp in ('pos', 'bl'):
        mode = 'pair'; B = fcls; A = a_ref(d, fcls)
    t0 = time.time()
    ext, U, PCC, coop, tag, li = restrict(d, init, fmask, fcls, mode, A, B)
    K = len(ext)
    rr = np.random.default_rng(ss); r1 = rr.random(K); r2 = rr.random(K)
    iDl = int(np.nonzero(ext == d['iD'])[0][0]) if (ext == d['iD']).any() else -1
    o = R_._kern(U, PCC, coop, tag, li, N, W, mN / N, ss, R_.checks_schedule(gens), True, iDl, r1, r2,
                 np.zeros(I, np.int64), 1)
    (st, sg, counts, isl_cc, isl_pay, trace, t_ext, held_zero, parent, t_est, e_arr, e_arrC, e_arrD, e_imm, e_hold, e_hloc,
     t90, a90, imm90, h90, hl90, arr_all, loss_log, nloss, first_sep, sep_a, sep_b, nsepchk, tr_log, ntr, mig_ct) = o
    root = np.arange(K)
    for x in range(K):
        r_ = x
        while parent[r_] != r_: r_ = parent[r_]
        root[x] = r_
    G = lambda x: nm[int(ext[x])] if x >= 0 else None
    glob = counts.sum(0)
    hold = np.array([R_.holder(counts[i]) for i in range(I)])
    estd = t_est >= 0
    loc_est = estd & (e_hloc >= 0.5)
    loc_end = loc_est & (root[np.maximum(e_hold, 0)] == hold)
    x = glob / glob.sum(); pr = np.nonzero(x)[0]
    cf = float(x[pr] @ PCC[np.ix_(pr, pr)] @ x[pr])
    cert_end = isl_cc >= 0.95
    r = dict(exp=exp, arm=arm, N=N, I=I, mN=mN, rep=rep, gens=gens, forced=forced, preset=preset,
             status=R_.STATUS[int(st)], stop_gen=int(sg), pcc=float(isl_cc.mean()), pcc_min=float(isl_cc.min()),
             cf_cross_pcc=cf, isl_eff=int(cert_end.sum()), n_est=int(estd.sum()), n_loc_est=int(loc_est.sum()),
             n_loc_end=int(loc_end.sum()), n_support=int(K), n_classes_end=int((glob > 0).sum()))
    r['t_est'] = [int(v) for v in t_est]
    r['final_trace'] = [float(v) for v in trace[-1]]
    w5 = np.nonzero(trace[:, 0] == 100000)[0]
    r['trace_1e5'] = [float(v) for v in trace[w5[0]]] if len(w5) else None
    hc = sorted({int(h) for i, h in enumerate(hold) if cert_end[i] and coop[h]})
    sep_end = [(a, b) for ai, a in enumerate(hc) for b in hc[ai + 1:] if U[a, b] == -1 and U[b, a] == -1]
    r['first_sep'] = int(first_sep); r['n_sep_end'] = len(sep_end)
    r['first_sep_pair'] = (G(root[sep_a]), G(root[sep_b])) if first_sep >= 0 else None
    r['sep_end_pairs'] = [(G(a), G(b)) for a, b in sep_end[:6]]
    r['sep'] = sep_intervals(trace)
    r['holders_end'] = dict(Counter(G(h) for h in hold).most_common(8))
    # every separation: rival source, bridge presence at seeding, bridge fate, resolution
    if first_sep >= 0 or sep_end:
        S = [('first', int(root[sep_a]), int(root[sep_b]))] if first_sep >= 0 else []
        S += [('end', a, b) for a, b in sep_end[:3]]
        Vx = d['V'][np.ix_(ext, ext)].astype(bool)
        VV = d['V'].astype(bool)
        a0g, a1g = d['src_cls'](FB), d['src_cls'](FB1)
        out = []
        for kind, a, b in S:
            ga, gb = int(ext[a]), int(ext[b])
            c = classify_pair(d, ga, gb)
            mcab = Vx[:, a] & Vx[a, :] & Vx[:, b] & Vx[b, :] & coop
            mcab[[a, b]] = False
            brl = np.nonzero(mcab)[0]
            if c['kind'] == 'A-rival':
                rg = c['rival_g']
                abr = np.array([bool(d['coop_s'][int(ext[k])] and int(ext[k]) not in (a0g, a1g)
                                     and VV[int(ext[k]), a0g] and VV[a0g, int(ext[k])] and VV[int(ext[k]), a1g]
                                     and VV[a1g, int(ext[k])] and VV[int(ext[k]), rg] and VV[rg, int(ext[k])]) for k in range(K)])
                c['A_bridge_seed'] = int(li[:, abr].sum()); c['A_bridge_alive_end'] = bool(glob[abr].sum() > 0)
            br_set = set(brl.tolist())
            med = 0; t_med = -1
            for g_, i_, a_, b_ in tr_log:
                if a_ >= 0 and b_ in br_set and root[a_] in (a, b):
                    med += 1
                    if t_med < 0: t_med = int(g_)
            c.update(when=kind, a=G(a), b=G(b), n_bridge_classes=int(len(brl)),
                     bridge_seed=int(li[:, brl].sum()) if len(brl) else 0,
                     bridge_seed_islands=int((li[:, brl].sum(1) > 0).sum()) if len(brl) else 0,
                     bridge_alive_end=bool(glob[brl].sum() > 0) if len(brl) else False,
                     bridge_held_end=int(np.isin(hold, brl).sum()) if len(brl) else 0,
                     mediations=med, t_first_med=t_med,
                     held_a=int((root[hold] == a).sum()), held_b=int((root[hold] == b).sum()))
            out.append(c)
        r['seps'] = out
    # tracked lineage (forced P* or the inert defector)
    if mode == 'track':
        f = K - 1
        r['lineage_end'] = int(glob[f]); r['lineage_alive_end'] = bool(glob[f] > 0)
        r['lineage_ext_gen'] = float(t_ext[1])
        r['lineage_max'] = float(trace[:, 1].max()); r['lineage_held_max'] = int(trace[:, 3].max())
        r['lineage_held_end'] = int((hold == f).sum())
        r['coop_est_lineage'] = int((estd & (e_hold >= 0) & (root[np.maximum(e_hold, 0)] == f)).sum())
        r['coop_hold_end_lineage'] = int(((hold == f) & cert_end).sum())
        r['founders'] = int(fmask.sum()); r['forced_cls'] = nm[fcls]
    # rival pair analysis (positive control / forced bridge-less rival): as bridgeless_rivals.job
    if mode == 'pair':
        held = {t: trace[:, 3 + (t - 1)] for t in (1, 2)}
        heldc = {t: trace[:, 5 + (t - 1)] for t in (1, 2)}
        g = trace[:, 0]
        htag = tag[hold]
        ev = np.nonzero((heldc[1] >= 1) & (heldc[2] >= 1))[0]
        r['ever_sep_tag'] = bool(len(ev) > 0); r['t_sep_tag'] = int(g[ev[0]]) if len(ev) else -1
        e2 = np.nonzero(heldc[2] >= 1)[0]
        r['rival_est'] = bool(len(e2) > 0); r['t_rival_est'] = int(g[e2[0]]) if len(e2) else -1
        loss_t = -1; loss_net = 0
        if len(ev):
            after = np.arange(ev[0], len(g))
            z1 = after[held[1][after] == 0]; z2 = after[held[2][after] == 0]
            c1 = int(g[z1[0]]) if len(z1) else -1; c2 = int(g[z2[0]]) if len(z2) else -1
            cands = [(c, k) for c, k in ((c1, 1), (c2, 2)) if c >= 0]
            if cands:
                loss_t, loss_net = min(cands)
        r['loss_t'] = loss_t; r['loss_net'] = loss_net
        tend = loss_t if loss_t >= 0 else float(sg)
        r['expo'] = IP.integ(trace, 3, 4, tend)
        r['sep_end_tag'] = bool(((htag == 1) & cert_end).any() and ((htag == 2) & cert_end).any())
        r['both_end'] = bool((htag == 1).any() and (htag == 2).any())
        r['held_end'] = {str(t): int((htag == t).sum()) for t in range(4)}
        etag = np.array([tag[h] if h >= 0 else -1 for h in e_hold])
        r['est_by_tag'] = {str(t): [int((estd & (etag == t) & (e_hloc >= 0.5)).sum()), int((estd & (etag == t) & (e_hloc < 0.5)).sum())]
                           for t in range(4)}
        b3 = tag == 3
        r['bridge_seed_islands'] = int((li[:, b3].sum(1) > 0).sum()); r['bridge_seed_copies'] = int(li[:, b3].sum())
        inv = Counter(); med_t = []
        for g_, i_, a_, b_ in tr_log:
            if a_ < 0: continue
            ta, tb = int(tag[a_]), int(tag[b_])
            if ta != tb:
                inv['%d>%d' % (ta, tb)] += 1
                if ta == 2 and tb == 3: med_t.append(int(g_))
        r['inv'] = dict(inv); r['n_med'] = len(med_t); r['t_med'] = med_t[0] if med_t else -1
        lim = loss_t if loss_t >= 0 else int(sg)
        r['med_before_end'] = bool(any(t <= lim for t in med_t))
        r['bridge_alive_end'] = bool(glob[b3].sum() > 0)
        r['bridge_held_end'] = int((htag == 3).sum())
        r['t_ext'] = [float(v) for v in t_ext]
    r['time_s'] = time.time() - t0
    return r


def boundary():
    c = json.load(open(CALIB))
    return dict(c['mN_boundary'])


def cells(exp):
    """(exp, arm, N, I, mN, reps, gens, forced, preset)."""
    out = []
    if exp == 'cal':
        for arm in ('free', 'K16', 'K4'):
            out.append(('cal', arm, 200, 16, 0.0, 120, GENS, None, 'iid'))
        return out
    B = boundary()
    if exp == 'nat':
        out.append(('nat', 'free', 200, 64, B['free'], 3000, GENS, None, 'iid'))
        out.append(('nat', 'K16', 200, 64, B['K16'], 3000, GENS, None, 'iid'))
        if abs(B['K16'] - B['free']) > 1e-9:
            out.append(('nat', 'K16', 200, 64, B['free'], 3000, GENS, None, 'iid'))
    elif exp == 'nat4':
        out.append(('nat', 'K4', 200, 64, B['K4'], 1000, GENS, None, 'iid'))
    elif exp == 'pos':
        out.append(('pos', 'K16', 200, 64, B['K16'], 100, GENS, POSCTRL, 'dense'))
    elif exp == 'pstar':
        for arm in ('K16', 'free'):
            out.append(('pstar', arm, 200, 64, B[arm], 100, GENS, PSTAR, 'dense'))
            out.append(('iid', arm, 200, 64, B[arm], 100, GENS, None, 'iid'))
        out.append(('dctl', 'K16', 200, 64, B['K16'], 100, GENS, 'D', 'dense'))
    return out


def ref_cells(exp):
    if exp != 'pstar':
        return []
    return [(e, arm, N, I, 0.0, reps, gens, f, pre) for e, arm, N, I, mN, reps, gens, f, pre in cells(exp)]


def rows_path(exp, ref=False):
    return os.path.join(RUNS, 'rivals-under-k-rows-%s%s.json.gz' % (exp, '-m0' if ref else ''))


def load(exp, ref=False):
    p = rows_path(exp, ref)
    return json.load(gzip.open(p, 'rt')) if os.path.exists(p) else []


def save(exp, rows, ref=False):
    def conv(o):
        if isinstance(o, np.integer): return int(o)
        if isinstance(o, np.floating): return float(o)
        if isinstance(o, np.ndarray): return o.tolist()
        if isinstance(o, np.bool_): return bool(o)
        raise TypeError(type(o))
    tmp = rows_path(exp, ref) + '.tmp'
    with gzip.open(tmp, 'wt') as f:
        json.dump(rows, f, default=conv)
    os.replace(tmp, rows_path(exp, ref))


def ckey(r):
    return (r['exp'], r['arm'], r['N'], r['I'], r['mN'], r['gens'], r['forced'], r['preset'])


def warm():
    for arm in ('free', 'K16', 'K4'):
        arm_table(arm); scr(arm)
    job(('time', 'K16', 20, 4, 1.0, 0, 50, None, 'iid'))


def run_main(a):
    from multiprocessing import Pool
    for ref in ((False, True) if a.ref else (False,)):
        rows = load(a.exp, ref)
        done = Counter(ckey(r) for r in rows)
        jobs = []
        for c in (ref_cells(a.exp) if ref else cells(a.exp)):
            e, arm, N, I, mN, reps, gens, f, pre = c
            key = (e, arm, N, I, mN, gens, f, pre)
            for rep in range(done[key], min(reps, a.maxreps)):
                jobs.append((e, arm, N, I, mN, rep, gens, f, pre))
        jobs.sort(key=lambda j: (j[5], j[1]))
        print('%s%s: %d jobs' % (a.exp, ' (m = 0 refs)' if ref else '', len(jobs)), flush=True)
        t0 = time.time()
        with Pool(a.procs, initializer=warm) as pool:
            for r in pool.imap_unordered(job, jobs):
                rows.append(r)
                print('%s %s mN=%g %s %s rep %d: %s gen %d pcc %.3f sep_end %d first_sep %d lin %s (%.1fs; %.0fs total)' % (
                    r['exp'], r['arm'], r['mN'], (r['forced'] or '-')[:30], r['preset'], r['rep'], r['status'], r['stop_gen'],
                    r['pcc'], r['n_sep_end'], r['first_sep'], r.get('lineage_alive_end', r.get('sep_end_tag')),
                    r['time_s'], time.time() - t0), flush=True)
                if len(rows) % 50 == 0:
                    save(a.exp, rows, ref)
        save(a.exp, rows, ref)


def calib_main(a):
    rows = load('cal')
    out = dict(T_nuc={}, dist={}, p={}, mN_boundary={}, n_nuc={}, x=0.3, N=200, I=16, runs={})
    for arm in ('free', 'K16', 'K4'):
        rs = [r for r in rows if r['arm'] == arm]
        if not rs: continue
        ts = np.array([t for r in rs for t in r['t_est'] if t >= 0], float)
        nis = sum(r['I'] for r in rs)
        T = float(np.median(ts))
        out['runs'][arm] = len(rs)
        out['T_nuc'][arm] = T; out['n_nuc'][arm] = [int(len(ts)), int(nis)]; out['p'][arm] = float(len(ts) / nis)
        out['dist'][arm] = {str(q): float(np.percentile(ts, q)) for q in (5, 10, 25, 50, 75, 90, 95)}
        out['mN_boundary'][arm] = round(0.3 * 200 / T, 3)
        rng = np.random.default_rng(1)
        per = [np.array([t for t in r['t_est'] if t >= 0]) for r in rs]
        bs = []
        for _ in range(2000):
            idx = rng.integers(0, len(per), len(per))
            v = np.concatenate([per[i] for i in idx])
            if len(v): bs.append(np.median(v))
        out['dist'][arm]['median_ci'] = [float(np.percentile(bs, 2.5)), float(np.percentile(bs, 97.5))]
    json.dump(out, open(CALIB, 'w'), indent=1)
    print(json.dumps(out, indent=1))


def cont_main(a):
    """(e): every natural run separated at the horizon and unresolved, continued to 3e5 generations from the same
    seeds (the kernel stream and the check schedule up to 1e5 are identical, so this extends the same trajectory;
    checked on the 1e5 check row)."""
    from multiprocessing import Pool
    nat = load('nat') + load('nat4')
    todo = [r for r in nat if r['n_sep_end'] > 0 and r['status'] == 'unresolved']
    rows = load('cont'); done = {(r['arm'], r['mN'], r['rep']) for r in rows}
    jobs = [('cont', r['arm'], r['N'], r['I'], r['mN'], r['rep'], 300000, None, 'iid') for r in todo
            if (r['arm'], r['mN'], r['rep']) not in done]
    if a.maxreps < len(jobs):
        jobs = jobs[:a.maxreps]
    print('cont: %d jobs' % len(jobs), flush=True)
    orig = {(r['arm'], r['mN'], r['rep']): r for r in todo}
    with Pool(a.procs, initializer=warm) as pool:
        for r in pool.imap_unordered(job, jobs):
            o = orig[(r['arm'], r['mN'], r['rep'])]
            r['matches_1e5'] = bool(r['trace_1e5'] is not None and np.allclose(r['trace_1e5'], o['final_trace']))
            rows.append(r); save('cont', rows)
            print('cont %s mN=%g rep %d: %s gen %d sep_end %d (was %d) matches %s (%.0fs)' % (
                r['arm'], r['mN'], r['rep'], r['status'], r['stop_gen'], r['n_sep_end'], o['n_sep_end'], r['matches_1e5'],
                r['time_s']), flush=True)


def timing_main(a):
    for j in [('time', 'free', 200, 64, 1.0, 0, GENS, None, 'iid'), ('time', 'K16', 200, 64, 1.0, 0, GENS, None, 'iid'),
              ('pstar', 'K16', 200, 64, 1.0, 0, 2000, PSTAR, 'dense'), ('pos', 'K16', 200, 64, 1.0, 0, 2000, POSCTRL, 'dense'),
              ('pstar', 'free', 200, 64, 1.0, 0, 2000, PSTAR, 'dense')]:
        r = job(j)
        print(j[0], j[1], j[7], r['status'], r['stop_gen'], '%.1fs' % r['time_s'], round(r['pcc'], 3),
              r.get('lineage_alive_end'), r.get('coop_est_lineage'), r.get('rival_est'), r.get('n_sep_end'), flush=True)


if __name__ == '__main__':
    ap = argparse.ArgumentParser()
    ap.add_argument('what', choices=['static', 'run', 'calib', 'cont', 'timing'])
    ap.add_argument('--exp', default='nat')
    ap.add_argument('--procs', type=int, default=3)
    ap.add_argument('--maxreps', type=int, default=10 ** 9)
    ap.add_argument('--ref', action='store_true')
    a = ap.parse_args()
    {'static': static_main, 'run': run_main, 'calib': calib_main, 'cont': cont_main, 'timing': timing_main}[a.what](a)
